"""Historical-incident corpus, separate from the evaluation dataset.

The corpus is generated by the same simulator but with its own seed (`rag.corpus_seed`, 7) and
its own scenario keys (``hist:<fault>:<n>``), so its incidents, resources and events are disjoint
from `synthetic-v1` by construction; `heldout_fingerprints` and the knowledge-base leakage
guard check it anyway (DECISIONS D62).

    python -m app.rag.corpus            # writes data/generated/historical-v1/
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from app.contracts.events import EventSource
from app.contracts.historical import HistoricalRecord
from app.contracts.taxonomy import FAULT_TYPES
from app.correlation.events import event_kind, message_template
from app.graph.store import node_type_for
from app.offline.dataset import DatasetLoader
from app.offline.faults import COMPATIBLE_TOPOLOGIES
from app.offline.models import ObservableScenario, TruthRecord
from app.offline.simulator import GENERATOR_VERSION, ScenarioSpec, generate_scenario

LABEL = "smoke-test / synthetic"
REPO = Path(__file__).resolve().parents[3]
DEFAULT_CORPUS_DIR = REPO / "data" / "generated" / "historical-v1"
DEFAULT_CORPUS_VERSION = "historical-v1"
DEFAULT_CORPUS_SEED = 7
VARIANTS_PER_FAULT = 4


def historical_plan() -> list[ScenarioSpec]:
    """4 past incidents per fault type, cycling through compatible topologies."""
    specs = []
    for fault in FAULT_TYPES:
        topos = COMPATIBLE_TOPOLOGIES[fault]
        for v in range(VARIANTS_PER_FAULT):
            specs.append(
                ScenarioSpec(
                    f"hist:{fault.value}:{v:02d}", "standard", (fault,), topos[v % len(topos)], v
                )
            )
    return specs


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def description_fingerprint(description: str) -> str:
    return "desc:" + _sha(description)


def record_from_scenario(
    obs: ObservableScenario, truth: TruthRecord, corpus_version: str, source: str
) -> HistoricalRecord:
    gt = truth.ground_truth
    by_id = {e.event_id: e for e in obs.events}
    evidence = [by_id[i] for i in gt.evidence_event_ids if i in by_id]
    lines: list[str] = []
    signals: set[str] = set()
    for e in evidence:
        if e.source == EventSource.CLOUDWATCH_METRIC:
            line = f"{e.metric} anomalous on {e.resource_id}"
            signals.add(f"metric:{e.metric}")
        elif e.source == EventSource.CLOUDWATCH_LOG:
            line = f"log on {e.resource_id}: {e.message}"
            signals.add(f"log:{message_template(e.message)}")
        else:
            line = f"{e.event_type} on {e.resource_id}: {e.message}"
            signals.add(f"{event_kind(e)}:{e.event_type}")
        if line not in lines:
            lines.append(line)
    alarm = next((e for e in obs.events if e.source == EventSource.ALARM), None)
    inc = obs.incident
    search_text = f"{inc.title}. {inc.description} Key signals: " + "; ".join(lines)
    summary = (
        f"{search_text}. Root cause ({gt.taxonomy_label.value}): {gt.root_cause_text} "
        f"Resolution: {gt.resolution}"
    )
    return HistoricalRecord(
        incident_id=inc.incident_id,
        corpus_version=corpus_version,
        source=source,
        title=inc.title,
        search_text=search_text,
        summary=summary,
        taxonomy_label=gt.taxonomy_label,
        root_cause_text=gt.root_cause_text,
        resolution=gt.resolution,
        alarm_metric=alarm.metric if alarm else None,
        signals=sorted(signals),
        resource_types=sorted(
            {node_type_for(r.resource_type, r.resource_id) for r in obs.resources}
        ),
        fingerprints=[
            inc.incident_id,
            description_fingerprint(inc.description),
            *gt.evidence_event_ids,
        ],
    )


def build_corpus(
    out_dir: str | Path = DEFAULT_CORPUS_DIR,
    seed: int = DEFAULT_CORPUS_SEED,
    version: str = DEFAULT_CORPUS_VERSION,
) -> list[HistoricalRecord]:
    records = []
    for spec in historical_plan():
        obs, truth = generate_scenario(spec, seed)
        records.append(record_from_scenario(obs, truth, version, "historical_corpus"))
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    body = json.dumps([r.model_dump(mode="json") for r in records], sort_keys=True, indent=1) + "\n"
    (out / "corpus.json").write_text(body, encoding="utf-8", newline="\n")
    manifest = {
        "corpus_version": version,
        "seed": seed,
        "generator_version": GENERATOR_VERSION,
        "label": LABEL,
        "count": len(records),
        "content_sha256": hashlib.sha256(body.encode()).hexdigest(),
        "scenario_key_prefix": "hist:",
    }
    (out / "manifest.json").write_text(
        json.dumps(manifest, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    return records


def load_corpus(path: str | Path = DEFAULT_CORPUS_DIR) -> list[HistoricalRecord]:
    data = json.loads((Path(path) / "corpus.json").read_text(encoding="utf-8"))
    return [HistoricalRecord.model_validate(r) for r in data]


def records_from_dataset(loader: DatasetLoader, split: str = "dev") -> list[HistoricalRecord]:
    """Dev incidents as a knowledge base for leave-one-out runs. The test split is refused."""
    if split != "dev":
        raise ValueError("only dev incidents may enter a knowledge base; test is never indexed")
    out = []
    for iid in loader.incident_ids("dev"):
        truth = loader.load_truth(iid)
        if not truth.ground_truth.evidence_event_ids:
            continue  # insufficient-evidence cases have no diagnosis worth retrieving
        out.append(
            record_from_scenario(
                loader.load(iid), truth, loader.manifest.dataset_version, "dataset_dev"
            )
        )
    return out


def heldout_fingerprints(loader: DatasetLoader) -> set[str]:
    """Everything that identifies a test incident: ids, every event id, description hashes."""
    out: set[str] = set()
    for iid in loader.incident_ids("test"):
        s = loader.load(iid)
        out.add(iid)
        out.add(description_fingerprint(s.incident.description))
        out.update(e.event_id for e in s.events)
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate the historical-incident corpus.")
    p.add_argument("--out", type=Path, default=DEFAULT_CORPUS_DIR)
    p.add_argument("--seed", type=int, default=DEFAULT_CORPUS_SEED)
    p.add_argument("--version", default=DEFAULT_CORPUS_VERSION)
    args = p.parse_args(argv)
    records = build_corpus(args.out, args.seed, args.version)
    print(f"[{LABEL}] wrote {len(records)} historical incidents to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
